### ISSUE TITLE
New Error for updated image. No longer able to acess webgui

### ISSUE THREAD

**Issue by SC8198** [Thomas-Philippot/removarr#16]
I pulled the new image and a new error has appeared.

Listening on http://0.0.0.0:3000
(node:1) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by Thomas-Philippot** [comment]
Hi, this warning is triggered by the [plex-api](https://github.com/phillipj/node-plex-api) package that I use to fetch the admin libraries.

Did you restarted the container with `docker compose up -d` again ? maybe try with the `--build` and  `--force-recreate` flags.

I just pushed a smaller image and it seems to be running just fine.

feel free to share you `compose.yaml` file if the web ui is still not available after that

**Comment by bobvmierlo** [comment]
I have the same issue on a fresh installed instance using the docker compose yaml below.

```yaml
services:
  removarr:
    container_name: removarr
    image: tphilippot/removarr:latest
    ports:
      - 3001:3000
    volumes:
      - ./config:/app/config
```

```
(node:1) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by Thomas-Philippot** [comment]
```js
 const client = new PlexApi({
    hostname: "192.168.1.181",
...
```
looks like I left my local plex server ip... 🫠

This should be a setting of course, i'm updating the app so you can setup this IP (with port as well)

**Comment by Thomas-Philippot** [comment]
Added a form on setup to set plex server ip / port.

This might require you to remove the `config/settings.json` file so the server regenerates a proper one.

**Comment by bobvmierlo** [comment]
> I removed the settings.json so it was regenerated.
> 
> I’m now able to login correctly, but sonarr and radarr are not reachable yet.
> 
> I set the correct IP addresses and ports (the same ones Overseerr is using without problems) and when I inspect the logs, it seems that it’s trying to connect to those without the port, even though it’s set.
> 
> Also, when I click on Test, I get both error and success messages, and in French, even though I have English set as my language.

Same here. Also the initial error by @SC8198 is still in the logs. And after going through the setup pages nothing happens when clicking 'Done'.

Also there seems to be some SSL handshake issue when trying to use this application behind a reverse proxy. I'm using NPM.

**Comment by Thomas-Philippot** [comment]
@bobvmierlo as you are using NPM like I do, I will recommend you prefix the hostname with "http" (or https if you set that up).

That way it should ignore the port and query your hostname directly.

On my settings I'm using "https://radarr.my-domain.com" as the hostname and it works great.

**Comment by Thomas-Philippot** [comment]
@bobvmierlo In this setup you should set "http://your-radarr-hostnam" in the hostname part of the `/setup` page 

This is my config (note that I have https)

![Screenshot_2025-05-23-21-09-01-30_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/user-attachments/assets/bcd4e866-e644-4bef-8055-f8745fb7cd41)

**Comment by Thomas-Philippot** [comment]
If you want to use ip instead of domain names you should not prefix with http
Just like so

![Screenshot_2025-05-23-21-12-07-46_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/user-attachments/assets/20f5f264-0132-49ce-b80a-c3d7ed35ba18)

**Comment by Thomas-Philippot** [comment]
@jlbnetwork Thanks for the feedback, I'm glad you made it work ☺️

I will improve the setup form based on that

**Comment by bobvmierlo** [comment]
I changed both Sonarr and Radarr options to the local IP and port. But nothing happens, even the logs stay empty.
I can see the page is trying to load briefly, but stays empty.
Both my Sonarr and Radarr instances are behind a Authentik login, that might be part of the issue? But my Overseerr is having no issues with reaching both instances (via the public URL).

**Comment by bobvmierlo** [comment]
The main page 'Votes' is visible and is showing the disk usage and votes, but there are not votes yet.
Also the users and settings page are working fine. Only 'Movies' and 'TV Shows' are empty.

![Image](https://github.com/user-attachments/assets/11bbebaa-b3a8-447f-8e71-d66b99723bf3)

**Comment by Thomas-Philippot** [comment]
Thanks for the answers !

If you see the disk usage it means that radarr API is working fine. The data are queried from the radarr api.

It might only be the images that are not loading? 🤔 Images are loaded from IMDb / tvdb 


The movie page should display an error message if an error occurred while fetching data from radarr

**Comment by bobvmierlo** [comment]
I did some more digging and I can see in the browser devtools that the request to /radarr/api/v3/movie is working and returning the JSON response with about 1600 items in there. That response also returns the image paths, for example "https://image.tmdb.org/t/p/original/uHpHzbHLSsVmAuuGuQSpyVDZmDc.jpg".
I also tried disabling everything that might block (AddBlock and Kasperky antivirus), no luck.

**Comment by Thomas-Philippot** [comment]
That's great !

1600 items ?

The browser is probably having a hard time loading / rendering all the images 

I should add pagination

**Comment by Thomas-Philippot** [comment]
Anyway I'm sorry you could not use the app yet.

I will look into this tomorrow and keep you updated

**Comment by SC8198** [comment]
I also am not able to load any shows or movies

![Image](https://github.com/user-attachments/assets/512bb4a5-2e55-4a6d-92f9-90bf99b2cc98)

**Comment by Thomas-Philippot** [comment]
Hi @SC8198 could you please provides theses informations :
- Is the storage information displaying on the main page ?
- How many movies do you have in your library

I just pushed a new release with pagination, could you try and tell me what that does ?

My library is pretty small so I don't really know how it can render with a lots of data.

@bobvmierlo I hope this new release helps you browser render the images correctly.

**Comment by bobvmierlo** [comment]
> Hi [@SC8198](https://github.com/SC8198) could you please provides theses informations :
> 
> * Is the storage information displaying on the main page ?
> * How many movies do you have in your library
> 
> I just pushed a new release with pagination, could you try and tell me what that does ?
> 
> My library is pretty small so I don't really know how it can render with a lots of data.
> 
> [@bobvmierlo](https://github.com/bobvmierlo) I hope this new release helps you browser render the images correctly.

Hi @Thomas-Philippot,

The movies tab is working now, but the series tab is still having issues. I can see the JSON results being pulled, but the webpage shows this error:

![Image](https://github.com/user-attachments/assets/be0850db-402f-4d8c-ad3a-af9ef3c9f0f3)

As you can see the API is reachable and returns the JSON response succesfully:

![Image](https://github.com/user-attachments/assets/1e4120af-38bd-4e6c-a7db-67b617c74869)

**Comment by Thomas-Philippot** [comment]
Thanks for the answer, I will look into this.

Have you updated the app to v2 ?

**Comment by bobvmierlo** [comment]
Yes I pulled the latest container (v2) via `docker compose pull` and then did `docker compose up -d`

**Comment by Thomas-Philippot** [comment]
Error should be displayed on that page (instead of the "check the Radarr/Sonarr settings" text) on the 2.0.1 release.

**Comment by bobvmierlo** [comment]
I pulled the new image and have this error on the page now:
```
Error while loading medias
Error: [GET] "/sonarr/api/v3/series": 401 Unauthorized
```

This is the output from the browser devconsole 'Network' tab for the GET request to http://192.168.2.68:3001/sonarr/api/v3/series
In the version before I did not have this issue. There the request worked and I say the JSON response from Sonarr, but nothing on the page. Now the internal API seems to be doing something unwanted.

```
{
  "error": true,
  "url": "http://192.168.2.68:3001/api/proxy/sonarr/api/v3/series",
  "statusCode": 401,
  "statusMessage": "Unauthorized",
  "message": "Server Error"
}
```

**Comment by Thomas-Philippot** [comment]
just fixed in #27

**Comment by Thomas-Philippot** [comment]
Hi, sorry for the wait, is the error exactly the same ?

**Comment by bobvmierlo** [comment]
Yes, still this one.

![Image](https://github.com/user-attachments/assets/dae1db3c-740f-4459-ab04-9a10ec87109f)
